name: Build and Deploy Spring Boot WAR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      war-file: ${{ steps.export.outputs.war-file }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build WAR with Maven
        run: mvn clean package -DskipTests

      - name: Find built WAR file
        id: export
        run: |
          FILE=$(find target -name "*.war" | head -n 1)
          echo "WAR file: $FILE"
          echo "war-file=$FILE" >> $GITHUB_OUTPUT

      - name: Upload WAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: springboot-war
          path: ${{ steps.export.outputs.war-file }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: MY_ENV
    steps:
      - name: Download WAR artifact
        uses: actions/download-artifact@v4
        with:
          name: springboot-war
          path: ./target

      - name: Check if secret is available
        run: |
          if [ -z "${{ secrets.EC2_USER }}" ]; then
            echo "Secret is NOT set"
          else
            echo "Secret is SET"
          fi
      
      - name: Show downloaded WAR
        run: ls -lh target

      - name: Save PEM key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > my-key.pem
          chmod 400 my-key.pem

      - name: Copy WAR to EC2
        run: |
          scp -i my-key.pem -o StrictHostKeyChecking=no ./target/*.war ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USER }}/ 

      - name: Deploy WAR to Tomcat
        run: |
          ssh -i my-key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            sudo mv /home/${USER}/*.war /opt/tomcat10/webapps/
            echo "Deployment successful!"
              

